name:                haskell-singer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haskell-singer#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - conduit
  - csv-conduit
  - containers
  - aeson
  - text

executables:
  haskell-singer:
    source-dirs:      src
    main:             Main.hs
